### ISSUE TITLE
Generar fichero de log con los intentos de acceso correctos e incorrectos.

### ISSUE THREAD

**Issue by uo68216** [Arquisoft/Agents_e3b#12]
Entre los requisitos de InciManager esta: 
"...
En caso de que la combinación "nombre de usuario/password" sea incorrecta, las incidencias no serán procesadas y se informará del error.
..."
Como la responsabilidad de validar los agentes está en este módulo se debería generar un fichero de log con los intentos de acceso correctos e incorrectos, sobre todo pensando en los intentos efectuados por los sensores.

**Comment by miguelms95** [comment]
@AndresAngelGG  Este Issue es de otro repositorio, además ya está hecho y cerrado: https://github.com/Arquisoft/InciManager_e3b/issues/14
