### ISSUE TITLE
Cambiar base de datos a HSQLDB

### ISSUE THREAD

**Issue by miguelms95** [Arquisoft/Agents_e3b#16]
En el pom añadir la dependencia hsqldb y eliminar la de hibernate (h2):

```
<dependency>
			<groupId>org.hsqldb</groupId>
			<artifactId>hsqldb</artifactId>
			<version> 2.4.0</version>
			<scope>runtime</scope>
		</dependency>
```

**Comment by miguelms95** [comment]
Ya funciona en local. Está a la espera de conseguir que Travis instancie una BD HSQLDB antes de comenzar el build, para que así no de error.

**Comment by kilianpg** [comment]
Referencias:
- [*Configuring Separate Spring DataSource for Tests*](http://www.baeldung.com/spring-testing-separate-data-source)

**Comment by miguelms95** [comment]
Hecho.
