### ISSUE TITLE
Cambios para leer del fichero maestro.

### ISSUE THREAD

**Issue by TonyMarin** [Arquisoft/Agents_e3b#8]
Tenemos que hacer los cambios que sean necesarios para leer nosotros también el fichero maestro .

El fichero maestro, en formato CSV, contiene los tipos de agentes disponibles. Tiene 2 campos separados por comas donde el primer campo es el código numérico y el segundo el nombre del tipo de usuario. Por ejemplo:
1,Person
2,Entity
3,Sensor

**Comment by miguelms95** [comment]
El CSV (fichero maestro) está en: [Agents_e3b/src/tipo_agentes.csv](https://github.com/Arquisoft/Agents_e3b/blob/master/src/tipo_agentes.csv)

**Comment by kilianpg** [comment]
Resuelto. He movido el fichero maestro al directorio 'recourses' y añadido al fichero 'application.properties' la propiedad 'csv.filepathname'.
